### ISSUE TITLE
How can I contribute to translate CATARSE?

### ISSUE THREAD

**Issue by perpi** [catarse/catarse#1293]
Is there any Transifex.com account for catarse?
(Note: transifex is free for open source project)

**Comment by adrianob** [comment]
Catarse just went through a major redesign so most english translations are outdated and there are still a lot of hardcoded strings. Moving the hardcoded strings to the translation files would help a lot. As for the translations themselves, it would probably be easier to copy the current portuguese translation structure and start from scratch.

**Comment by hminaya** [comment]
@adrianob is this still outdated, has this been improved? Can I contribute to this?

**Comment by finkiki** [comment]
It appear that catarse team don't care a lot about others languages. A lot of time passed without any credible translation possibilities.

**Comment by diogob** [comment]
@finkiki I'm sorry for our current state of translations. But we have a very small team and our main focus is to keep our platform running. Any help is welcome, we are currently using the rails translation files, so they can be translated, and if you want to help us organizing it a bit by removing unused entries it would make future contributions easier ;)

Actually @adrianob 's suggestion is still valid. And no, we are not moving to online translation services like Transifex because we tried several and they all are harder to maintain than the standard Rails way.
