### ISSUE TITLE
Can't Login on app launched heroku

### ISSUE THREAD

**Issue by oudin** [catarse/catarse#1298]
Hi
I've recently launched this app on heroku however I can't login after after entering the credentials I'm just redirected to the home page.

LInk: https://pure-depths-2749.herokuapp.com/en

How can I solve this. 

Thanks in advance.

**Comment by lewispb** [comment]
Same issue here

**Comment by pinak1180** [comment]
hello @oudin  can you please tell me how you managed it to work.? am too facing the same issue.

**Comment by devton** [comment]
@oudin @lewispb I can simulate the issue here, you can see the full error commenting line 3 of application_controller.
I get the error "No route matches {:action=>"passthru", :controller=>"omniauth_callbacks", :locale=>"pt", :provider=>:facebook} missing required keys: [:provider]"
If is the same error you need to configure the facebook auth keys or just run rake db:seed to populate with fake facebook oauth provider:
OauthProvider.find_or_create_by!(name: 'facebook') do |o|
  o.key = 'your_facebook_app_key'
  o.secret = 'your_facebook_app_secret'
  o.path = 'facebook'
end
