### ISSUE TITLE
Error with successful completion migrations at Amazon RDS

### ISSUE THREAD

**Issue by kozeyandrey** [catarse/catarse#2460]
Hello, guys

We deployed our app to Heroku and connect Amazon RDS database to our app. When we run a command "heroku run rake db:migrate" we get this error by AddSchema1ToSearchPath (https://www.dropbox.com/s/2z142vvqwcmwvr2/Screenshot%202017-01-17%2022.26.30.png?dl=0)
We don't know what is the reason.
Please, help us solve it.

**Comment by vicnicius** [comment]
Hello @kozeyandrey. The problem here is with the name of your database. Typically postgres databases should avoid hyphens on it's name, though you could simply use quotes around it. In this case, the migration is not using quotes, which is leading to this syntax error. Renaming the database should fix this issue.

**Comment by kozeyandrey** [comment]
Got it. It works. Thanks, @vicnicius
