### ISSUE TITLE
Question: Why are ENVs saved the database?

### ISSUE THREAD

**Issue by ACPK** [catarse/catarse#2609]
Why are ENVs saved in the database rather than in an env file that can be encrypted?

**Comment by vicnicius** [comment]
What kind of ENVs are you talking about, @ACPK?

**Comment by mikesmayer** [comment]
@vicnicius, i think what @ACPK means is how come you're using a Settings table to store config variables that might best be stored as ENV variables?

i believe this is a practice advocated by https://12factor.net/config

**Comment by ACPK** [comment]
@mikesmayer -Thanks Mike.

**Comment by devton** [comment]
@ACPK @mikesmayer we are using settings on database because some settings are used inside the database too.

The CatarseSettings module is abstract to github.com/catarse/catarse_settings_db if you want you can create a catarse_settings_env thats use ENV vars instead database table but you still need to change the way that some configurations are get via SQL
