### ISSUE TITLE
Postgrest roles and permissions issues using AWS RDS

### ISSUE THREAD

**Issue by hugodemiglio** [catarse/catarse#2831]
I'm using postgres on AWS RDS (PostgreSQL 9.6.2).

How can I configure permissions and roles for Postgrest?

I have tried this:
```
GRANT anonymous TO catarse;
GRANT admin TO catarse;
GRANT web_user TO catarse;
```

But I still getting errors like:

/contribution_details?order=id.desc
`permission denied for relation contribution_details`

/balance_transactions?order=created_at.desc&user_id=eq.7
`permission denied for relation balance_transactions`

**Comment by caiotarifa** [comment]
@hugodemiglio, have you had any luck with this?

I'm experiencing a similar problem here, in my case I running with PostgreSQL 9.4 on macOS.

![](https://user-images.githubusercontent.com/197979/32625960-019126f0-c575-11e7-8be3-ed594129d6f7.png)

The email be `null` when a non-admin user logs in. As I understand it, I think the problem happens because the `web_user` role is getting data from `1` schema instead of `public`.

I don't know what I'm doing wrong.

**Comment by hugodemiglio** [comment]
Using the last versions of PostgREST the problem was solved. I think this should be updated in the `README.md`.
